name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and test
      run: |
        for dir in $(ls -d */); do
          echo "Building and testing $dir"
          cargo build --verbose
          cargo test --verbose
          cd ..
        done
